CREATE TABLE IF NOT EXISTS appointments (
  id INT PRIMARY KEY AUTO_INCREMENT,
  customer_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  service_type VARCHAR(255) NOT NULL,
  car_make VARCHAR(255) NOT NULL,
  car_model VARCHAR(255) NOT NULL,
  car_year VARCHAR(10),
  plate_number VARCHAR(50),
  fuel_type VARCHAR(50),
  appointment_date DATE NOT NULL,
  appointment_time VARCHAR(20) NOT NULL,
  description TEXT,
  status ENUM('Pending', 'In Progress', 'Completed', 'Cancelled') NOT NULL DEFAULT 'Pending',
  labor_cost DECIMAL(10,2) DEFAULT 0,
  assigned_employee_id INT NULL,
  completed_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (assigned_employee_id) REFERENCES employees(id)
);
